### PR TITLE
issue #52

### PR DESCRIPTION
**Pull request by michaelfliegner**
Integer on 64Bit Architecture is BIGINT in POSTGRES.
Testing integers for containment in int8ranges for instance requires a cast to BIGINT. I do not want my keys restricted to 32bit.

My change to BIGINT may be the trigger for the problem but imho the cause would rather be a parser quirk that confuses a limit clause with a type cast in the context of not being aware of the BIGINT type. But, of course, the easiest cure is to retract that map of INTEGER to BIGINT and add an own clause for BIGINT

### CODE REVIEW

**Comment by michaelfliegner** [comment]
passes CI of my client package BitemporalPostgres

**Comment by michaelfliegner** [comment]
> What about `:binary => :BLOB,`? Imho it should be `:binary => :BYTEA,`? [Wrong PostgreSQL types in SearchLightPostgreSQL.TYPE_MAPPINGS #11](https://github.com/GenieFramework/SearchLightPostgreSQL.jl/issues/11#issue-1179909735)
@UniqueTokens Maybe You create a PRQ for that? I feel resonsible for **this**, as it relates to a former PRQ of mine and I researched Date/Time data types for Julia and Postgres. I do not have the time to research BLOB types for now.
PS: This type mapping part of the package is a wee fragile imo. For instance Integer is abstract in Julia and 32bit in POSTGRES.
So to be safe we should use: Int16 => smallint, Int32 => integer, Int64 => bigint But I do not know how that might impact SearchLight.jl

**Comment by UniqueTokens** [comment]
> PS: This type mapping part of the package is a wee fragile imo.

I agree with that. @essenciary It might make sense to discuss the timeline and all the pros and cons of the current SearchLight implementation in a team of contributors before a new PRQ for BYTEA? For my part, I'm currently thinking about whether and how the hardcoded `SearchLightPostgreSQL.TYPE_MAPPINGS` could be replaced by a dynamic assignment using the type conversions in the already used `LibPQ.jl`.

**Comment by essenciary** [comment]
I agree - however, one of the goals is to provide as much compatibility between the various DB adapters so migrations can be ported between backends. So we should keep common mappings (shared with MySQL, SQLite, etc common types) and additional/specialised mappings for Postgres.

**Comment by essenciary** [comment]
@michaelfliegner @UniqueTokens lmk if you agree that this is good to merge and I'll proceed.

**Comment by michaelfliegner** [comment]
Ok with me

**Comment by UniqueTokens** [comment]
LGTM

**Comment by essenciary** [comment]
Thanks guys!

**Pull request merged**
