### PR TITLE
 Adding to :timestamptz and :tstzrange to TYPE_MAPPING

### PR DESCRIPTION
**Pull request by Kaeptenblaubaer**
This version is incremental and thus should not interfere with apps not interested in timestamps and intervals.

### CODE REVIEW

**Review by essenciary — COMMENTED** [review]
Thank you! 

1/ can we please keep the casing consistent? ie: 
`:int4range => :INT4RANGE`

2/ the `Symbol("Interval{ZonedDateTime}") label seems hard to use by library users. Can't we have 
`:tzrange => :TSTZRANGE` ? 

3/ Can't we have 
`timestamptz => :TIMESTAMPTZ` 

The idea is to keep things consistent in terms of casing an naming as much as possible, to make it easier and predictable on the users.

**Comment by Kaeptenblaubaer** [comment]
OK. I'm a julia beginner and it was just a first try to get s.th. working. I will change the request following Your suggestions.

**Comment by essenciary** [comment]
No problem - thanks for the PR!

**Comment by Kaeptenblaubaer** [comment]
Tzpecase conventions corrected and BIGINT added

**Comment by Kaeptenblaubaer** [comment]
Hi!
Is there still any obstacle to merging my request?
My project on Bitemporal Data Management, which depends on SearchLightPostgreSQL.jl, is approaching its first deployment to Julia Registry. And we can't register packages with unregistered dependencies, can we?

best regards
Michael Fliegner
see:
https://github.com/Kaeptenblaubaer/BitemporalPostgres

**Comment by essenciary** [comment]
Merged

**Comment by michaelfliegner** [comment]
Integer on 64Bit Architecture is BIGINT in POSTGRES. 
Testing integers for containment in  int8ranges for instance requires a cast to BIGINT. I do not want my keys restricted to 32bit.

My change to BIGINT may be the trigger for the problem but imho the cause would rather be parser quirk that does not know about BIGINT, only INTEGER.

So please don't revert. I can try to help on the basis of my assumption.

**Comment by michaelfliegner** [comment]
Integer on 64Bit Architecture is BIGINT in POSTGRES. 
Testing integers for containment in  int8ranges for instance requires a cast to BIGINT. I do not want my keys restricted to 32bit.

My change to BIGINT may be the trigger for the problem but imho the cause would rather be parser quirk that does not know about BIGINT, only INTEGER.

So please don't revert. I can try to help on the basis of my assumption.

A first idea would be, to restore the clause for :integer and  ADD a clause  
> :bigint => BIGINT
That should not be break anything anymore.

Should I create that PRQ?

**Pull request merged**
